export type NavCategory = {
  title: string;
  brands: string[];
};

export const SECONDARY_NAV_DATA: NavCategory[] = [
  {
    title: "Disposable / Pods System",
    brands: [
      "Air Bar",
      "myBlu",
      "EB Create",
      "Elux Astra",
      "Geek Bar", 
      "HorizonTech",
      "JUUL",
      "Logic",
      "LUFF BAR",
      "One Tank",
      "Peak Bar",
      "RAZ",
      "ROMO",
      "TasteFlex",
      "TYN",
      "VINT",
      "Volf Bar",
      "VIHO",
      "VUSE",
      "YOVO",
    ],
  },
  {
    title: "E Liquids & Salt Nic",
    brands: [
      "Air Factory E-Liquids",
      "BAMS",
      "Beard Vape Co",
      "Bar Juice",
      "Cloud Nurdz",
      "Cali Juice",
      "Coastal Clouds",
      "Four Seasons",
      "Ferrum City Liquid",
      "Halo Eliquids",
      "Juice Head",
      "Keep It 100",
      "Micro Brew Vapors",
      "Mighty Vapors",
      "Monster Vape Labs",
      "Nasty eJuice",
      "Naked100",
      "Really Good Juice Co",
      "Reds Apple 7 Daze",
      "Ripe Vapes",
      "Salt Bae 50",
      "Vapergate",
      "Vapetasia",
      "VGOD XL VAPE",
      "Yogi E-Liquids",
      "Zenith Ejuice",
      "Zooka",
    ],
  },
  {
    title: "Devices / Pods / Coils / Tanks",
    brands: [
      "Geek Vape",
      "Smok Tech",
      "Suorin",
      "Uwell",
      "Vaporesso",
      "Voopoo",
    ],
  },
  {
    title: "Smoke Shop",
    brands: [
      "Batteries / Chargers",
      "Butane Fuel",
      "Candles / Spray / Incense",
      "CCELL & iKrusher",
      "Dry Herb & Wax Vaporizers",
      "Fronto Leaf",
      "Glass Cleaner",
      "Grinders",
      "HY BIRD Glass",
      "Lighters",
      "Male Enhancements",
      "Papers & Wraps",
      "The Power Hitter",
      "Zippo",
    ],
  },
];
